### ISSUE TITLE
Creación de las entidades (básico)

### ISSUE THREAD

**Issue by nataliaMarzec** [ingsw-sarmiento/libro-matriz-digital#42]
Depende de #34.

**Criterios de aceptación**
* Tienen que estar creadas todas las entidades que están en el MER.
* Cada entidad debe tener al menos un atributo y los necesarios para armar las relaciones.

**Comment by vgrana** [comment]
@JuanCS95  @faloi 
Juan, está bien, lo único que veo que estaría faltando para cumplir el criterio "....los necesarios para armar las relaciones " sería en la clase Cursada el atributo Exámen.

**Comment by faloi** [comment]
@vgrana, comentá en el pull request, no acá. En este caso deberías no aprobarlo, porque estás pidiendo cambios.

**Comment by faloi** [comment]
La issue se cierra solo al mergear el pull request (de hecho para eso ponemos el `closes #...`). La reabro para seguir el procedimiento.
